name: JsxposedX
description: "flutter for hook"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 6.0.1+601

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  go_router: ^16.2.5
  cached_network_image: ^3.4.1
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  flutter_smart_dialog: ^4.9.8+9
  fluttertoast: ^8.2.8
  json_annotation: ^4.9.0
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.0.0
  crypto: ^3.0.7
  encrypt: ^5.0.3
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  flutter_cache_manager: ^3.4.1
  package_info_plus: ^9.0.0
  pigeon: ^26.1.0
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^3.1.0
  device_info_plus: ^12.3.0
  storage_space: ^1.2.0
  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.5.41
  path: ^1.9.1
  re_editor: ^0.8.0
  re_highlight: ^0.0.3
  flutter_markdown: ^0.7.7+1
  uuid: ^4.5.3
  url_launcher: ^6.3.2
  custom_pop_up_menu: ^1.2.4
  popover: ^0.4.0
  file_picker: ^10.3.10
  flutter_staggered_grid_view: ^0.7.0
  flutter_quill: ^11.5.0
  flutter_quill_extensions: ^11.0.0
  flutter_quill_delta_from_html: ^1.5.3
  flutter_html: ^3.0.0
  markdown: ^7.3.1
  marquee: ^2.3.0
  external_app_launcher: ^4.0.3
  flutter_floating: ^2.0.2
  flutter_overlay_window: ^0.5.0
  liquid_glass_widgets: ^0.5.0







dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  riverpod_generator: ^3.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  drift_dev: ^2.29.0
flutter:
  generate: true  # 启用国际化代码生成


  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/raws/
  fonts:
    - family: AliMama
      fonts:
        - asset: assets/fonts/alimama_fang_yuan.ttf


flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/logo.png

dependency_overrides:
  flutter_overlay_window:
    path: third_party/flutter_overlay_window


# Pigeon 配置已迁移至外部文件 pigeon.yaml
# 使用以下命令运行更新：
# flutter pub run pigeon --config-file pigeon.yaml
